# Generated by Django 3.0.8 on 2020-08-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200803_0927'),
        ('images', '0003_auto_20200803_0940'),
    ]

    operations = [
    ]
