# Generated by Django 3.0.9 on 2020-08-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200803_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
