# Generated by Django 3.0.9 on 2020-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categories',
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(to='images.categories'),
        ),
    ]
